Lesson 9: Add posts and comments with API
ErofeevAA/fefu_backend_2_3 pull request #11
Opened 2022-01-07 16:55 UTC by ErofeevAA

2022-01-07 16:56 UTC, ErofeevAA commented
Поломал историю, пришлось перезаливать

2022-01-10 15:10 UTC, chrn-feip requested changes

2022-01-10 15:10 UTC, chrn-feip commented on app/Http/Controllers/PostController.php
> +        $posts = Post::with('user')->ordered()->paginate(self::PAGE_SIZE);
with('user', 'comments'), иначе комментарии будут вычитывать отдельными запросами к Бд для каждого поста на странице списка. А лучше бы вычитать для всех постов страницы комменты одним запросом, with это позволит сделать как раз.

2022-01-10 15:10 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> +            'text' => 'sometimes|required|max:150'
sometimes тут не имеет смысла, т.е. всего один атрибут ожидается для обновления.

2022-01-10 15:10 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> +        return $post->comments()->ordered()->paginate(self::PAGE_SIZE);
..->comments()->with('user')->..., иначе неоптимальное количество запросов в БД за автором каждого коммента

2022-01-11 11:43 UTC, merged