Lesson 10: Add web and API auth and profile
ErofeevAA/fefu_backend_2_3 pull request #12
Opened 2022-01-07 17:08 UTC by ErofeevAA

2022-01-10 15:22 UTC, chrn-feip requested changes

2022-01-10 15:22 UTC, chrn-feip commented on app/Models/User.php
> +        'login' => 'required|between:5,30|unique:users,login',
Не хватает ограничений на алфавит:

> допускаются латинские буквы в любом регистре, цифры, дефис, знак подчёркивания

2022-01-10 15:22 UTC, chrn-feip commented on app/Http/Resources/PostResource.php
> +            'comments' => CommentResource::collection($this->comments),
Это должно быть в коде предыдущего PR

2022-01-10 15:22 UTC, chrn-feip commented on app/Http/Controllers/WebAuthController.php
> +        auth('web')->logout();
Тут guard web, а в веб-маршруте sanctum. Нестыковочка.

2022-01-16 08:45 UTC, chrn-feip commented
Устраните конфликты

2022-01-16 09:27 UTC, ErofeevAA commented
> Устраните конфликты

готово

2022-01-16 12:34 UTC, merged